/**
 * MarkdownPRDContent.tsx — Animated markdown PRD file aesthetic.
 *
 * Renders as a realistic .md file with:
 *   - File header bar (filename, /create-prd attribution)
 *   - YAML-style frontmatter (dim, instant)
 *   - Section headers (## in accent color)
 *   - ISC items in `- [ ]` / `- [x]` notation, revealed sequentially
 *
 * Used in demo-skill-prd-03 to show the PRD created by /create-prd —
 * clearly conveys "this is a markdown requirements file, not a checklist UI".
 */

import React from "react";
import { interpolate, useCurrentFrame } from "remotion";

const MD_BG        = "#0D1117"; // GitHub dark
const MD_TEXT      = "#E6EDF3";
const MD_DIM       = "#6E7681";
const MD_GREEN     = "#3FB950"; // checked items
const MD_BLUE      = "#79C0FF"; // section headers
const MD_AMBER     = "#E3B341"; // frontmatter keys / tag badges
const MD_PURPLE    = "#D2A8FF"; // ISC Verify method
const MD_CHECKBOX  = "#58A6FF"; // [ ] / [x] brackets
const DIVIDER      = "#21262D";

export interface PRDItem {
  text: string;
  tag: string;
  checked?: boolean;
  verify?: string;
}

export interface MarkdownPRDContentProps {
  /** Frame at which ISC items start revealing (default 20) */
  startFrame?: number;
  /** Frames between each ISC item reveal (default 24) */
  itemDelay?: number;
  /** ISC items to display */
  items: PRDItem[];
  /** PRD title (shown in h2 header) */
  title?: string;
  /** Phase label shown in frontmatter */
  phase?: string;
}

export const MarkdownPRDContent: React.FC<MarkdownPRDContentProps> = ({
  startFrame = 20,
  itemDelay = 24,
  items,
  title = "create-demo-video",
  phase = "Phase 1 — MVP",
}) => {
  const frame = useCurrentFrame();

  return (
    <div
      style={{
        fontFamily: "'Cascadia Code', 'Fira Code', 'Courier New', monospace",
        fontSize: 15,
        lineHeight: 1.7,
        color: MD_TEXT,
        backgroundColor: MD_BG,
        borderRadius: 10,
        overflow: "hidden",
        height: "100%",
        display: "flex",
        flexDirection: "column",
      }}
    >
      {/* ── File tab bar ── */}
      <div
        style={{
          display: "flex",
          alignItems: "center",
          gap: 10,
          padding: "10px 18px",
          backgroundColor: "#161B22",
          borderBottom: `1px solid ${DIVIDER}`,
          flexShrink: 0,
        }}
      >
        <span style={{ fontSize: 18, color: "#58A6FF" }}>📄</span>
        <span style={{ color: MD_TEXT, fontWeight: 600, fontSize: 14 }}>
          memory/work/{title}/PRD.md
        </span>
        <span
          style={{
            marginLeft: "auto",
            fontSize: 12,
            color: MD_DIM,
            fontFamily: "system-ui, -apple-system, sans-serif",
            letterSpacing: "0.05em",
          }}
        >
          generated by /create-prd
        </span>
      </div>

      {/* ── File content ── */}
      <div style={{ padding: "18px 24px", flex: 1, overflow: "hidden" }}>

        {/* Frontmatter */}
        <div style={{ color: MD_DIM, marginBottom: 14 }}>
          <div>---</div>
          <div>
            <span style={{ color: MD_AMBER }}>skill</span>
            <span style={{ color: MD_DIM }}>: </span>
            <span style={{ color: "#A5D6FF" }}>create-demo-video</span>
          </div>
          <div>
            <span style={{ color: MD_AMBER }}>phase</span>
            <span style={{ color: MD_DIM }}>: </span>
            <span style={{ color: "#A5D6FF" }}>{phase}</span>
          </div>
          <div>
            <span style={{ color: MD_AMBER }}>isc_gate</span>
            <span style={{ color: MD_DIM }}>: </span>
            <span style={{ color: MD_GREEN }}>PASS (6/6)</span>
          </div>
          <div>---</div>
        </div>

        {/* H2 section header */}
        <div
          style={{
            color: MD_BLUE,
            fontWeight: 700,
            fontSize: 17,
            marginBottom: 16,
          }}
        >
          ## ACCEPTANCE CRITERIA
        </div>

        {/* ISC items — revealed sequentially */}
        {items.map((item, i) => {
          const revealFrame = startFrame + i * itemDelay;
          const elapsed = Math.max(0, frame - revealFrame);
          const op = interpolate(elapsed, [0, 8], [0, 1], {
            extrapolateLeft: "clamp",
            extrapolateRight: "clamp",
          });
          const ty = interpolate(elapsed, [0, 8], [10, 0], {
            extrapolateLeft: "clamp",
            extrapolateRight: "clamp",
          });

          const isChecked = item.checked ?? false;

          return (
            <div
              key={i}
              style={{
                opacity: op,
                transform: `translateY(${ty}px)`,
                marginBottom: 6,
                display: "flex",
                alignItems: "flex-start",
                gap: 4,
              }}
            >
              {/* - */}
              <span style={{ color: MD_DIM, flexShrink: 0 }}>-</span>
              {/* checkbox */}
              <span style={{ color: MD_CHECKBOX, flexShrink: 0 }}>
                {isChecked ? "[x]" : "[ ]"}
              </span>
              {/* item text */}
              <span style={{ color: isChecked ? MD_GREEN : MD_TEXT, flex: 1 }}>
                {item.text}
              </span>
              {/* tag */}
              <span
                style={{
                  color: MD_AMBER,
                  fontSize: 12,
                  fontFamily: "system-ui, -apple-system, sans-serif",
                  backgroundColor: "rgba(227, 179, 65, 0.12)",
                  padding: "1px 7px",
                  borderRadius: 4,
                  flexShrink: 0,
                  alignSelf: "center",
                }}
              >
                {item.tag}
              </span>
            </div>
          );
        })}

        {/* Verify method line — appears after last item */}
        {(() => {
          const lastReveal = startFrame + (items.length - 1) * itemDelay + 12;
          const el = Math.max(0, frame - lastReveal);
          const op = interpolate(el, [0, 8], [0, 1], {
            extrapolateLeft: "clamp",
            extrapolateRight: "clamp",
          });
          return (
            <div style={{ opacity: op, marginTop: 14, color: MD_DIM, fontSize: 13 }}>
              <span style={{ color: MD_PURPLE }}>| Verify: </span>
              <span>npx remotion render + ffmpeg concat + file-exists check</span>
            </div>
          );
        })()}
      </div>
    </div>
  );
};
