#!/usr/bin/env python3
"""Validate agent definition files against the Six-Section anatomy."""

import argparse
import os
import re
import sys


REQUIRED_SECTIONS = [
    "Identity",
    "Mission",
    "Critical Rules",
    "Deliverables",
    "Workflow",
    "Success Metrics",
]

AGENTS_DIR = os.path.join(
    os.path.dirname(__file__), "..", "..", "orchestration", "agents"
)


def find_sections(content):
    """Extract h2 headings from markdown content."""
    headings = re.findall(r"^## (.+)$", content, re.MULTILINE)
    return [h.strip() for h in headings]


def check_agent(filepath):
    """Check a single agent file for required sections. Returns (name, found, missing)."""
    name = os.path.splitext(os.path.basename(filepath))[0]
    with open(filepath, "r", encoding="utf-8") as f:
        content = f.read()

    headings = find_sections(content)
    found = []
    missing = []
    for section in REQUIRED_SECTIONS:
        if any(section.lower() in h.lower() for h in headings):
            found.append(section)
        else:
            missing.append(section)

    return name, found, missing


def inject_agent_tasks(failures):
    """Inject pending_review tasks for agents missing required sections.

    Uses routine_id dedup so the same agent won't generate duplicate tasks
    while it remains non-compliant. Returns count of newly injected tasks.
    """
    try:
        import sys
        from pathlib import Path
        repo_root = Path(__file__).resolve().parents[2]
        sys.path.insert(0, str(repo_root))
        from tools.scripts.lib.backlog import backlog_append
    except ImportError:
        return 0

    injected = 0
    for name, missing in failures:
        task = {
            "description": (
                f"Fix agent {name}: missing Six-Section anatomy sections: "
                f"{', '.join(missing)}"
            ),
            "tier": 1,
            "priority": 4,
            "autonomous_safe": False,
            "status": "pending_review",
            "routine_id": f"agent_anatomy_{name}",
            "isc": [
                f"Agent {name} passes Six-Section anatomy validation "
                f"| Verify: python tools/scripts/validate_agents.py"
            ],
            "notes": (
                f"Auto-generated by validate_agents.py. "
                f"Missing sections: {', '.join(missing)}."
            ),
            "context_files": [
                f"orchestration/agents/{name}.md",
            ],
        }
        result = backlog_append(task)
        if result is not None:
            injected += 1

    return injected


def main():
    parser = argparse.ArgumentParser(
        description="Validate agent definitions against the Six-Section anatomy."
    )
    parser.add_argument(
        "--dir",
        default=AGENTS_DIR,
        help="Directory containing agent .md files (default: orchestration/agents/)",
    )
    parser.add_argument(
        "--verbose", "-v", action="store_true", help="Show per-agent section details"
    )
    args = parser.parse_args()

    agents_dir = os.path.normpath(args.dir)
    if not os.path.isdir(agents_dir):
        print("Error: directory not found: %s" % agents_dir)
        sys.exit(2)

    md_files = sorted(
        [f for f in os.listdir(agents_dir) if f.endswith(".md")]
    )

    if not md_files:
        print("No .md files found in %s" % agents_dir)
        sys.exit(2)

    results = []
    for md_file in md_files:
        filepath = os.path.join(agents_dir, md_file)
        name, found, missing = check_agent(filepath)
        results.append((name, found, missing))

    # Print summary table (ASCII only)
    header = "%-20s %-8s %-40s" % ("Agent", "Score", "Missing Sections")
    print(header)
    print("-" * len(header))

    all_pass = True
    for name, found, missing in results:
        score = "%d/6" % len(found)
        missing_str = ", ".join(missing) if missing else "(none)"
        print("%-20s %-8s %-40s" % (name, score, missing_str))
        if args.verbose and found:
            print("  Found: %s" % ", ".join(found))
        if missing:
            all_pass = False

    print()
    print("Agents checked: %d" % len(results))
    print("Required sections: %s" % ", ".join(REQUIRED_SECTIONS))

    if all_pass:
        print("Result: ALL PASS")
        sys.exit(0)
    else:
        failures = [(name, missing) for name, _, missing in results if missing]
        failing_names = [name for name, _ in failures]
        print("Result: FAIL -- %d agent(s) missing sections: %s" % (len(failing_names), ", ".join(failing_names)))
        injected = inject_agent_tasks(failures)
        if injected:
            print("Injected %d backlog task(s) for non-compliant agents." % injected)
        sys.exit(1)


if __name__ == "__main__":
    main()
